services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
      - ./input:/app/input
      - ./output:/app/output
    command: python3 main.py